Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -44,14 +44,15 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v2
 
-      - name: Rebuild Docker Image
-        run: docker build -t hello-devops:latest .
-
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
+      - name: Pull Docker Image from Docker Hub
+        run: |
+          docker pull nadajoobeur/hello-devops:v1.0 || echo "Image already exists locally or failed to pull"
+
       - name: Tag Docker Image
-        run: docker tag hello-devops:latest nadajoobeur/hello-devops:v1.0
+        run: docker tag nadajoobeur/hello-devops:v1.0 nadajoobeur/hello-devops:v1.0
 
       - name: Push Docker Image
         run: docker push nadajoobeur/hello-devops:v1.0
